<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <PackageId>patagona.$(AssemblyName)</PackageId>
        <Authors>patagona</Authors>
        <Description>A .NET Client for the Android Debug Bridge (ADB)</Description>
        <PackageProjectUrl>https://github.com/patagonaa/AdbClient.NET</PackageProjectUrl>
        <PackageTags>adb;android;android-debug-bridge</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/patagonaa/AdbClient.NET.git</RepositoryUrl>
        <Version>6.0.0</Version>
        <PackageReleaseNotes>
            - fix: upgrade SixLabors.ImageSharp to non-vulnerable version
            - fix: target .NET 8.0 as .NET Standard is no longer required and .NET 6.0 is out of support
        </PackageReleaseNotes>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1573;1591</NoWarn>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\CHANGELOG.md" Pack="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

</Project>
